# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # setup:
   # runs-on: ubuntu-latest
  #  strategy:
  #   matrix: 
   #   value: [test,test3]
   # steps:
     # - run: |
    #     echo "${{ matrix.value }}" 
         
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        test=(app,orange)
        IFS=','
        test2=${{test[@]}}
        echo "::set-output name=matrix::$(echo test2 | jq -R -s -c 'split("\n")[:-1]')"
  job2: 
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.project }}
  #build:
   # needs: [ setup ]
    #runs-on: ubuntu-latest
   # strategy:
    #  matrix:
     #   value: ${{fromJson(needs.setup.outputs.matrix)}}
    #steps:
      #- run: |
        #  echo "${{ matrix.value }}"
